"""empty message

Revision ID: 0001_f8838f69092c_migration
Revises: 
Create Date: 2026-02-22 19:14:11.516677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.decorators

# revision identifiers, used by Alembic.
revision: str = '0001_f8838f69092c_migration'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_establishments_id'), 'establishments', ['id'], unique=False)
    op.create_index(op.f('ix_establishments_name'), 'establishments', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', app.core.decorators.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('authorized', 'has_irregularities', 'finalized', 'finalized_prohibition', 'finalized_partial_prohibition', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_establishments_name'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_id'), table_name='establishments')
    op.drop_table('establishments')
    # ### end Alembic commands ###
