"""empty message

Revision ID: 0002_a707ab52b4e8_migration
Revises: 0001_f8838f69092c_migration
Create Date: 2026-02-22 19:16:06.784037

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import app
from app.core.security import get_password_hash
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_a707ab52b4e8_migration'
down_revision: Union[str, None] = '0001_f8838f69092c_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hashed_password = get_password_hash('12345')
    op.bulk_insert(
        sa.Table(
            'users',
            sa.MetaData(),
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('username', sa.String(60), nullable=False),
            sa.Column('full_name', sa.String(255), nullable=False),
            sa.Column('email', sa.String(100), nullable=False),
            sa.Column('role', app.core.decorators.Integer(), nullable=False),
            sa.Column('hashed_password', sa.String(255), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False, default=datetime.now),
            sa.Column('created_at', sa.DateTime(), nullable=False, default=datetime.now),
        ),
        [
            {'id': 1, 'username': 'super', 'full_name': 'super', 'email': 'super@example.com', 'hashed_password': hashed_password, 'role': 1},
        ]
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
