"""empty message

Revision ID: 0003_2807d21402d5_migration
Revises: 0002_a707ab52b4e8_migration
Create Date: 2026-02-22 21:01:34.588471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.decorators

# revision identifiers, used by Alembic.
revision: str = '0003_2807d21402d5_migration'
down_revision: Union[str, None] = '0002_a707ab52b4e8_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspections', 'status',
               existing_type=postgresql.ENUM('authorized', 'has_irregularities', 'finalized', 'finalized_prohibition', 'finalized_partial_prohibition', name='status'),
               type_=app.core.decorators.Integer(),
               existing_nullable=False,
               postgresql_using="""CASE
                       WHEN status = 'authorized' THEN 1
                       WHEN status = 'has_irregularities' THEN 2
                       WHEN status = 'finalized' THEN 3
                       WHEN status = 'finalized_prohibition' THEN 4
                       WHEN status = 'finalized_partial_prohibition' THEN 5
                       ELSE 1
                   END::integer
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspections', 'status',
               existing_type=app.core.decorators.Integer(),
               type_=postgresql.ENUM('authorized', 'has_irregularities', 'finalized', 'finalized_prohibition', 'finalized_partial_prohibition', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###
