"""empty message

Revision ID: 0004_675f27537cfd_migration
Revises: 0003_2807d21402d5_migration
Create Date: 2026-02-22 23:33:54.436026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.decorators

# revision identifiers, used by Alembic.
revision: str = '0004_675f27537cfd_migration'
down_revision: Union[str, None] = '0003_2807d21402d5_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('old_status', app.core.decorators.Integer(), nullable=False),
    sa.Column('new_status', app.core.decorators.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_log_id'), 'inspection_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_log_id'), table_name='inspection_log')
    op.drop_table('inspection_log')
    # ### end Alembic commands ###
