"""empty message

Revision ID: 0005_f492a6379e0f_migration
Revises: 0004_675f27537cfd_migration
Create Date: 2026-02-22 23:40:21.176898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.decorators

# revision identifiers, used by Alembic.
revision: str = '0005_f492a6379e0f_migration'
down_revision: Union[str, None] = '0004_675f27537cfd_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irregularities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('severity', app.core.decorators.Integer(), nullable=False),
    sa.Column('requires_interruption', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irregularities_description'), 'irregularities', ['description'], unique=False)
    op.create_index(op.f('ix_irregularities_id'), 'irregularities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irregularities_id'), table_name='irregularities')
    op.drop_index(op.f('ix_irregularities_description'), table_name='irregularities')
    op.drop_table('irregularities')
    # ### end Alembic commands ###
