"""empty message

Revision ID: 0006_7b15336a60e3_migration
Revises: 0005_f492a6379e0f_migration
Create Date: 2026-02-23 02:31:18.715657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.decorators

# revision identifiers, used by Alembic.
revision: str = '0006_7b15336a60e3_migration'
down_revision: Union[str, None] = '0005_f492a6379e0f_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finalization_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('status', app.core.decorators.Integer(), nullable=False),
    sa.Column('pending_issues', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finalization_log_id'), 'finalization_log', ['id'], unique=False)
    op.create_table('irregularities_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('irregularity_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('old_severity', app.core.decorators.Integer(), nullable=False),
    sa.Column('new_severity', app.core.decorators.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['irregularity_id'], ['irregularities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irregularities_log_id'), 'irregularities_log', ['id'], unique=False)
    op.add_column('inspection_log', sa.Column('inspector_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inspection_log', 'users', ['inspector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspection_log', type_='foreignkey')
    op.drop_column('inspection_log', 'inspector_id')
    op.drop_index(op.f('ix_irregularities_log_id'), table_name='irregularities_log')
    op.drop_table('irregularities_log')
    op.drop_index(op.f('ix_finalization_log_id'), table_name='finalization_log')
    op.drop_table('finalization_log')
    # ### end Alembic commands ###
