"""empty message

Revision ID: f67ed1b73865
Revises: 792a23d86dc5
Create Date: 2026-02-21 22:04:02.611841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67ed1b73865'
down_revision: Union[str, None] = '792a23d86dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('superuser', 'inspector', name='roleenum'), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
